task:
  name: rom
  timeout_in: 120m
  container:
    dockerfile: Dockerfile
    cpu: 8
    memory: 32G
  environment:
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[d79606ef07066fa4c032a3d6856423ec8800f30f7ce5e7636e67d6edcd8f69d654788762ece25de098731ce535e917eb]"
    CHATID: -1001180021426
    BOTTOKEN: 1815669550:AAEbRHnnqNe1z1EYQ7L1Dww56VklR2Y6k1Y
    TDRIVE: http://idk.krishiv8190.workers.dev
  download_ccache_background_script:
      - bash download_ccache.sh
  upload_ccache_background_script:
      - bash upload_ccache.sh
  build_script:
      - bash build.sh
  final_upload_ccache_script:
      - bash final_upload_ccache.sh
